-- AlterTable
ALTER TABLE `users` MODIFY `username` VARCHAR(191) NULL,
    MODIFY `activete_at` DATETIME(3) NULL,
    MODIFY `address_ine2` VARCHAR(191) NULL,
    MODIFY `address_line1` VARCHAR(191) NULL,
    MODIFY `avatar` VARCHAR(191) NULL,
    MODIFY `city` VARCHAR(191) NULL,
    MODIFY `country` VARCHAR(191) NULL,
    MODIFY `country_code` VARCHAR(191) NULL,
    MODIFY `created_at` DATETIME(3) NULL DEFAULT CURRENT_TIMESTAMP(3),
    MODIFY `email_confirmed` BOOLEAN NULL DEFAULT false,
    MODIFY `extra_config` VARCHAR(191) NULL,
    MODIFY `geo_location` VARCHAR(191) NULL,
    MODIFY `is_active` BOOLEAN NULL DEFAULT false,
    MODIFY `landmark` VARCHAR(191) NULL,
    MODIFY `phone` VARCHAR(191) NULL,
    MODIFY `photo_url` VARCHAR(191) NULL,
    MODIFY `remember_token` VARCHAR(191) NULL,
    MODIFY `state` VARCHAR(191) NULL,
    MODIFY `two_factor_code` VARCHAR(191) NULL,
    MODIFY `updated_att` DATETIME(3) NULL,
    MODIFY `zipcode` VARCHAR(191) NULL;
